package oracle.apps.hcm.formulas.core.jerseyTest;

import oracle.apps.hcm.formulas.core.jersey.api.*;
import oracle.apps.hcm.formulas.core.jersey.config.*;
import oracle.apps.hcm.formulas.core.jersey.model.*;
import oracle.apps.hcm.formulas.core.jersey.parser.*;
import oracle.apps.hcm.formulas.core.jersey.parser.AstNodes.*;
import oracle.apps.hcm.formulas.core.jersey.parser.AstNodes;
import oracle.apps.hcm.formulas.core.jersey.service.*;

import org.junit.Test;

import static org.junit.Assert.*;

/**
 * Mirrors test_formula_templates.py (7 tests).
 */
public class FormulaTypesServiceTest {

    private final FormulaTypesService service = new FormulaTypesService();

    @Test
    public void allTypesLoads() {
        var types = service.listAll();
        assertTrue("Expected >= 100 types, got " + types.size(), types.size() >= 100);
    }

    @Test
    public void eachTypeHasRequiredFields() {
        for (var t : service.listAll()) {
            assertNotNull("Missing type_name", t.get("type_name"));
        }
    }

    @Test
    public void getTemplateReturnsTemplate() {
        var tmpl = service.getTemplate("Oracle Payroll");
        assertNotNull(tmpl);
        assertEquals("Oracle Payroll", tmpl.get("display_name"));
    }

    @Test
    public void getTemplateUnknownReturnsNull() {
        assertNull(service.getTemplate("NONEXISTENT_TYPE"));
    }

    @Test
    public void oraclePayrollTemplate() {
        var tmpl = service.getTemplate("Oracle Payroll");
        assertNotNull(tmpl);
        String skeleton = (String) tmpl.get("skeleton");
        assertTrue(skeleton.contains("Oracle Payroll"));
    }

    @Test
    public void skeletonHasFormulaNamePlaceholder() {
        // Check a sample of templates have {formula_name}
        var tmpl = service.getTemplate("Oracle Payroll");
        assertNotNull(tmpl);
        String skeleton = (String) tmpl.get("skeleton");
        assertTrue("skeleton missing {formula_name}", skeleton.contains("{formula_name}"));
    }

    @Test
    public void autoGeneratedTypesAvailable() {
        for (String tn : new String[]{"Flow Schedule", "Batch Loader", "Net to Gross", "Element Skip"}) {
            var tmpl = service.getTemplate(tn);
            assertNotNull(tn + " template not found", tmpl);
            String skeleton = (String) tmpl.get("skeleton");
            assertTrue(tn + " has empty skeleton", skeleton.length() > 50);
        }
    }
}
