-- FF_FORMULA_TEMPLATES_TL
-- View returning all rows and columns from "ff_formula_templates_tl".
-- Fusion pattern: the physical translation table has a lowercase, double-quoted
-- name so that EBR can manage edition-based redefinition; user-facing code
-- references the uppercase view name.

CREATE OR REPLACE VIEW FF_FORMULA_TEMPLATES_TL AS
SELECT
    TEMPLATE_ID,
    LANGUAGE,
    NAME,
    SOURCE_LANG,
    DESCRIPTION,
    OBJECT_VERSION_NUMBER,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    LAST_UPDATED_BY,
    ENTERPRISE_ID,
    SEED_DATA_SOURCE,
    ORA_SEED_SET1,
    ORA_SEED_SET2
FROM "ff_formula_templates_tl";

CREATE TABLE "ff_formula_templates_tl" 
(
  TEMPLATE_ID NUMBER(18, 0) NOT NULL 
, LANGUAGE VARCHAR2(4) NOT NULL 
, NAME VARCHAR2(240) NOT NULL 
, SOURCE_LANG VARCHAR2(4) NOT NULL 
, DESCRIPTION VARCHAR2(4000) 
, OBJECT_VERSION_NUMBER NUMBER(9, 0) DEFAULT 1 NOT NULL 
, CREATED_BY VARCHAR2(64) NOT NULL 
, CREATION_DATE TIMESTAMP NOT NULL 
, LAST_UPDATE_DATE TIMESTAMP NOT NULL 
, LAST_UPDATE_LOGIN VARCHAR2(32) 
, LAST_UPDATED_BY VARCHAR2(64) NOT NULL 
, ENTERPRISE_ID NUMBER(18, 0) DEFAULT nvl(SYS_CONTEXT('FND_VPD_CTX','FND_ENTERPRISE_ID'), 0) NOT NULL 
, SEED_DATA_SOURCE VARCHAR2(512) DEFAULT SYS_CONTEXT('FND_SDF_CTX', 'SDFFILE') NOT NULL 
, ORA_SEED_SET1 VARCHAR2(1) DEFAULT 'Y' NOT NULL 
, ORA_SEED_SET2 VARCHAR2(1) DEFAULT 'Y' NOT NULL 
)