
GRANT SELECT ON FF_FORMULA_TEMPLATES TO FUSION_RUNTIME;
GRANT SELECT ON FF_FORMULA_TEMPLATES_TL TO FUSION_RUNTIME;
GRANT UPDATE ON FF_FORMULA_TEMPLATES TO FUSION_RUNTIME;
GRANT UPDATE ON FF_FORMULA_TEMPLATES_TL TO FUSION_RUNTIME;
GRANT INSERT ON FF_FORMULA_TEMPLATES TO FUSION_RUNTIME;
GRANT INSERT ON FF_FORMULA_TEMPLATES_TL TO FUSION_RUNTIME;
GRANT DELETE ON FF_FORMULA_TEMPLATES TO FUSION_RUNTIME;
GRANT DELETE ON FF_FORMULA_TEMPLATES_TL TO FUSION_RUNTIME;
GRANT SELECT ON FF_FORMULA_TEMPLATES_VL TO FUSION_RUNTIME;

select * from FF_FORMULA_TEMPLATES_VL where name = 'Overtime Pay Calculation';


delete from FF_FORMULA_TEMPLATES_VL where formula_type_id is not null;



ALTER TABLE "ff_formula_templates"
ADD (SYSTEMPROMPT_FLAG VARCHAR2(1) DEFAULT 'N');


SET SQLBLANKLINES ON
CREATE TABLE "ff_formula_templates" 
(
  TEMPLATE_ID NUMBER(18, 0) NOT NULL 
, FORMULA_TYPE_ID NUMBER(18, 0) 
, TEMPLATE_CODE VARCHAR2(150) NOT NULL 
, FORMULA_TEXT CLOB 
, ADDITIONAL_PROMPT_TEXT CLOB 
, SOURCE_TYPE VARCHAR2(30) NOT NULL 
, ACTIVE_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL 
, SEMANTIC_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL 
, SORT_ORDER NUMBER(9, 0) 
, OBJECT_VERSION_NUMBER NUMBER(9, 0) DEFAULT 1 NOT NULL 
, LAST_UPDATE_DATE TIMESTAMP NOT NULL 
, CREATED_BY VARCHAR2(64) NOT NULL 
, CREATION_DATE TIMESTAMP NOT NULL 
, LAST_UPDATED_BY VARCHAR2(64) NOT NULL 
, LAST_UPDATE_LOGIN VARCHAR2(32) 
, ENTERPRISE_ID NUMBER(18, 0) DEFAULT nvl(SYS_CONTEXT('FND_VPD_CTX','FND_ENTERPRISE_ID'), 0) NOT NULL 
, SEED_DATA_SOURCE VARCHAR2(512) DEFAULT SYS_CONTEXT('FND_SDF_CTX', 'SDFFILE') NOT NULL 
, MODULE_ID VARCHAR2(32) 
, ORA_SEED_SET1 VARCHAR2(1) DEFAULT 'Y' NOT NULL 
, ORA_SEED_SET2 VARCHAR2(1) DEFAULT 'Y' NOT NULL 
, CONSTRAINT FF_FORMULA_TEMPLATES_PK PRIMARY KEY 
  (
    TEMPLATE_ID 
  )
  DISABLE 
) ;

CREATE TABLE "ff_formula_templates_tl" 
(
  TEMPLATE_ID NUMBER(18, 0) NOT NULL 
, LANGUAGE VARCHAR2(4) NOT NULL 
, NAME VARCHAR2(240) NOT NULL 
, SOURCE_LANG VARCHAR2(4) NOT NULL 
, DESCRIPTION VARCHAR2(4000) 
, OBJECT_VERSION_NUMBER NUMBER(9, 0) DEFAULT 1 NOT NULL 
, CREATED_BY VARCHAR2(64) NOT NULL 
, CREATION_DATE TIMESTAMP NOT NULL 
, LAST_UPDATE_DATE TIMESTAMP NOT NULL 
, LAST_UPDATE_LOGIN VARCHAR2(32) 
, LAST_UPDATED_BY VARCHAR2(64) NOT NULL 
, ENTERPRISE_ID NUMBER(18, 0) DEFAULT nvl(SYS_CONTEXT('FND_VPD_CTX','FND_ENTERPRISE_ID'), 0) NOT NULL 
, SEED_DATA_SOURCE VARCHAR2(512) DEFAULT SYS_CONTEXT('FND_SDF_CTX', 'SDFFILE') NOT NULL 
, ORA_SEED_SET1 VARCHAR2(1) DEFAULT 'Y' NOT NULL 
, ORA_SEED_SET2 VARCHAR2(1) DEFAULT 'Y' NOT NULL 
, CONSTRAINT FF_FORMULA_TEMPLATES_TL_PK PRIMARY KEY 
  (
    TEMPLATE_ID 
  , LANGUAGE 
  )
  DISABLE 
) 
LOGGING 
PCTFREE 40 
PCTUSED 60 
INITRANS 10 
STORAGE 
( 
  INITIAL 4 
  NEXT 1 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  FREELISTS 4 
  FREELIST GROUPS 32 
  BUFFER_POOL DEFAULT 
);

CREATE OR REPLACE VIEW FF_FORMULA_TEMPLATES AS
SELECT
    fft.TEMPLATE_ID TEMPLATE_ID,
    fft.FORMULA_TYPE_ID FORMULA_TYPE_ID,
    fft.TEMPLATE_CODE TEMPLATE_CODE,
    fft.FORMULA_TEXT FORMULA_TEXT,
    fft.ADDITIONAL_PROMPT_TEXT ADDITIONAL_PROMPT_TEXT,
    fft.SOURCE_TYPE SOURCE_TYPE,
    fft.SYSTEMPROMPT_FLAG SYSTEMPROMPT_FLAG,
    fft.ACTIVE_FLAG ACTIVE_FLAG,
    fft.SEMANTIC_FLAG SEMANTIC_FLAG,
    fft.SORT_ORDER SORT_ORDER,
    fft.SEED_DATA_SOURCE SEED_DATA_SOURCE,
    fft.CREATED_BY CREATED_BY,
    fft.CREATION_DATE CREATION_DATE,
    fft.LAST_UPDATE_DATE LAST_UPDATE_DATE,
    fft.LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN,
    fft.LAST_UPDATED_BY LAST_UPDATED_BY,
    fft.MODULE_ID MODULE_ID,
    fft.ENTERPRISE_ID ENTERPRISE_ID,
    fft.OBJECT_VERSION_NUMBER OBJECT_VERSION_NUMBER
FROM "ff_formula_templates" fft;

CREATE OR REPLACE VIEW FF_FORMULA_TEMPLATES_TL AS
SELECT
    TEMPLATE_ID,
    LANGUAGE,
    NAME,
    SOURCE_LANG,
    DESCRIPTION,
    OBJECT_VERSION_NUMBER,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    LAST_UPDATED_BY,
    ENTERPRISE_ID,
    SEED_DATA_SOURCE,
    ORA_SEED_SET1,
    ORA_SEED_SET2
FROM "ff_formula_templates_tl";




CREATE OR REPLACE VIEW FF_FORMULA_TEMPLATES_VL
AS SELECT
    fft.TEMPLATE_ID TEMPLATE_ID,
    fft.FORMULA_TYPE_ID FORMULA_TYPE_ID,
    fft.TEMPLATE_CODE TEMPLATE_CODE,
    fft.FORMULA_TEXT FORMULA_TEXT,
    fft.ADDITIONAL_PROMPT_TEXT ADDITIONAL_PROMPT_TEXT,
    fft.SOURCE_TYPE SOURCE_TYPE,
    fft.SYSTEMPROMPT_FLAG SYSTEMPROMPT_FLAG,
    fft.ACTIVE_FLAG ACTIVE_FLAG,
    fft.SEMANTIC_FLAG SEMANTIC_FLAG,
    fft.SORT_ORDER SORT_ORDER,
    fft.SEED_DATA_SOURCE SEED_DATA_SOURCE,
    fft.CREATED_BY CREATED_BY,
    fft.CREATION_DATE CREATION_DATE,
    fft.LAST_UPDATE_DATE LAST_UPDATE_DATE,
    fft.LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN,
    fft.LAST_UPDATED_BY LAST_UPDATED_BY,
    fft.MODULE_ID MODULE_ID,
    fft.ENTERPRISE_ID ENTERPRISE_ID,
    fft.OBJECT_VERSION_NUMBER OBJECT_VERSION_NUMBER,
    ffttl.NAME NAME,
    ffttl.DESCRIPTION DESCRIPTION
FROM
    FF_FORMULA_TEMPLATES fft,
    FF_FORMULA_TEMPLATES_TL ffttl
WHERE
    fft.TEMPLATE_ID = ffttl.TEMPLATE_ID AND ffttl.LANGUAGE = USERENV('LANG');
