SELECT fat.module_id,
  fat.module_name,
  fat.module_type
FROM FND_APPL_TAXONOMY fat,
  (SELECT source_module_id
  FROM FND_APPL_TAXONOMY_HIERARCHY fath
    CONNECT BY prior fath.target_module_id = fath.source_module_id
    START WITH fath.source_module_id IN
    (SELECT module_id
    FROM FND_APPL_TAXONOMY
    WHERE module_name like 'HcmPayCore'
    )
  ) module_id
WHERE fat.module_id = module_id.source_module_id;

--6345B48C2F5A8CB4E040449821C64847
--6345B48C2F3C8CB4E040449821C64847
--6345B48C2F3D8CB4E040449821C64847
--61ECAF4AAB01E990E040449821C61C97
SELECT fat.module_id,
  fat.module_name,
  fat.module_type
FROM FND_APPL_TAXONOMY fat,
  (SELECT source_module_id
  FROM FND_APPL_TAXONOMY_HIERARCHY fath
    CONNECT BY prior fath.target_module_id = fath.source_module_id
    START WITH fath.source_module_id IN
    (SELECT module_id
    FROM FND_APPL_TAXONOMY
    WHERE module_id = '6345B48C2E118CB4E040449821C64847'
    )
  ) module_id
where fat.module_id = module_id.source_module_id;
-----------------------------------------------------------------

GRANT SELECT ON FF_FORMULA_TEMPLATES TO FUSION_RUNTIME;
GRANT SELECT ON FF_FORMULA_TEMPLATES_TL TO FUSION_RUNTIME;
GRANT UPDATE ON FF_FORMULA_TEMPLATES TO FUSION_RUNTIME;
GRANT UPDATE ON FF_FORMULA_TEMPLATES_TL TO FUSION_RUNTIME;
GRANT INSERT ON FF_FORMULA_TEMPLATES TO FUSION_RUNTIME;
GRANT INSERT ON FF_FORMULA_TEMPLATES_TL TO FUSION_RUNTIME;
GRANT DELETE ON FF_FORMULA_TEMPLATES TO FUSION_RUNTIME;
GRANT DELETE ON FF_FORMULA_TEMPLATES_TL TO FUSION_RUNTIME;
GRANT SELECT ON FF_FORMULA_TEMPLATES_VL TO FUSION_RUNTIME;


select * from FF_FORMULA_TEMPLATES_VL where template_code = 'ORA_HCM_FF_SYSTEM_PROMPT';
select * from "ff_formula_templates_tl" where template_id in (300100646124592, 100106861372618);
select * from "ff_formula_templates" where template_id in (300100646124592, 100106861372618);


delete from "ff_formula_templates" where template_id in (300100646124592, 100106861372618);

update ff_formula_templates_tl set description = 'Complete Oracle Fusion Cloud HCM Fast Formula language specification for LLM code generation. Covers data types, statement ordering, operators, control flow, built-in functions, formula type output contracts, naming conventions, and guardrails against hallucinated syntax.' where template_id = 300100646125593;

update ff_formula_templates set module_id = '61ECAF4AABAFE911E040449821C61C97' where template_id = 300100646125592;
update "ff_formula_templates_tl" set name = 'Fast Formula Language Reference', description = 'Complete Oracle Fusion Cloud HCM Fast Formula language specification for LLM code generation — covers data types, statement ordering, operators, control flow, built-in functions, formula type output contracts, naming conventions, and anti-hallucination rules.' where template_id = 100106861371859;

select * from ff_formula_types;

delete from ff_formula_templates_tl where template_id in (select template_id from FF_FORMULA_TEMPLATES_VL where formula_type_id is not null);
delete from ff_formula_templates where formula_type_id is not null;


ALTER TABLE "ff_formula_templates"
ADD (SYSTEMPROMPT_FLAG VARCHAR2(1) DEFAULT 'N');


SET SQLBLANKLINES ON
CREATE TABLE "ff_formula_templates" 
(
  TEMPLATE_ID NUMBER(18, 0) NOT NULL 
, FORMULA_TYPE_ID NUMBER(18, 0) 
, TEMPLATE_CODE VARCHAR2(150) NOT NULL 
, FORMULA_TEXT CLOB 
, ADDITIONAL_PROMPT_TEXT CLOB 
, SOURCE_TYPE VARCHAR2(30) NOT NULL 
, ACTIVE_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL 
, SEMANTIC_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL 
, SORT_ORDER NUMBER(9, 0) 
, OBJECT_VERSION_NUMBER NUMBER(9, 0) DEFAULT 1 NOT NULL 
, LAST_UPDATE_DATE TIMESTAMP NOT NULL 
, CREATED_BY VARCHAR2(64) NOT NULL 
, CREATION_DATE TIMESTAMP NOT NULL 
, LAST_UPDATED_BY VARCHAR2(64) NOT NULL 
, LAST_UPDATE_LOGIN VARCHAR2(32) 
, ENTERPRISE_ID NUMBER(18, 0) DEFAULT nvl(SYS_CONTEXT('FND_VPD_CTX','FND_ENTERPRISE_ID'), 0) NOT NULL 
, SEED_DATA_SOURCE VARCHAR2(512) DEFAULT SYS_CONTEXT('FND_SDF_CTX', 'SDFFILE') NOT NULL 
, MODULE_ID VARCHAR2(32) 
, ORA_SEED_SET1 VARCHAR2(1) DEFAULT 'Y' NOT NULL 
, ORA_SEED_SET2 VARCHAR2(1) DEFAULT 'Y' NOT NULL 
, CONSTRAINT FF_FORMULA_TEMPLATES_PK PRIMARY KEY 
  (
    TEMPLATE_ID 
  )
  DISABLE 
) ;

CREATE TABLE "ff_formula_templates_tl" 
(
  TEMPLATE_ID NUMBER(18, 0) NOT NULL 
, LANGUAGE VARCHAR2(4) NOT NULL 
, NAME VARCHAR2(240) NOT NULL 
, SOURCE_LANG VARCHAR2(4) NOT NULL 
, DESCRIPTION VARCHAR2(4000) 
, OBJECT_VERSION_NUMBER NUMBER(9, 0) DEFAULT 1 NOT NULL 
, CREATED_BY VARCHAR2(64) NOT NULL 
, CREATION_DATE TIMESTAMP NOT NULL 
, LAST_UPDATE_DATE TIMESTAMP NOT NULL 
, LAST_UPDATE_LOGIN VARCHAR2(32) 
, LAST_UPDATED_BY VARCHAR2(64) NOT NULL 
, ENTERPRISE_ID NUMBER(18, 0) DEFAULT nvl(SYS_CONTEXT('FND_VPD_CTX','FND_ENTERPRISE_ID'), 0) NOT NULL 
, SEED_DATA_SOURCE VARCHAR2(512) DEFAULT SYS_CONTEXT('FND_SDF_CTX', 'SDFFILE') NOT NULL 
, ORA_SEED_SET1 VARCHAR2(1) DEFAULT 'Y' NOT NULL 
, ORA_SEED_SET2 VARCHAR2(1) DEFAULT 'Y' NOT NULL 
, CONSTRAINT FF_FORMULA_TEMPLATES_TL_PK PRIMARY KEY 
  (
    TEMPLATE_ID 
  , LANGUAGE 
  )
  DISABLE 
) 
LOGGING 
PCTFREE 40 
PCTUSED 60 
INITRANS 10 
STORAGE 
( 
  INITIAL 4 
  NEXT 1 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  FREELISTS 4 
  FREELIST GROUPS 32 
  BUFFER_POOL DEFAULT 
);

CREATE OR REPLACE VIEW FF_FORMULA_TEMPLATES AS
SELECT
    fft.TEMPLATE_ID TEMPLATE_ID,
    fft.FORMULA_TYPE_ID FORMULA_TYPE_ID,
    fft.TEMPLATE_CODE TEMPLATE_CODE,
    fft.FORMULA_TEXT FORMULA_TEXT,
    fft.ADDITIONAL_PROMPT_TEXT ADDITIONAL_PROMPT_TEXT,
    fft.SOURCE_TYPE SOURCE_TYPE,
    fft.SYSTEMPROMPT_FLAG SYSTEMPROMPT_FLAG,
    fft.ACTIVE_FLAG ACTIVE_FLAG,
    fft.SEMANTIC_FLAG SEMANTIC_FLAG,
    fft.SORT_ORDER SORT_ORDER,
    fft.SEED_DATA_SOURCE SEED_DATA_SOURCE,
    fft.CREATED_BY CREATED_BY,
    fft.CREATION_DATE CREATION_DATE,
    fft.LAST_UPDATE_DATE LAST_UPDATE_DATE,
    fft.LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN,
    fft.LAST_UPDATED_BY LAST_UPDATED_BY,
    fft.MODULE_ID MODULE_ID,
    fft.ENTERPRISE_ID ENTERPRISE_ID,
    fft.OBJECT_VERSION_NUMBER OBJECT_VERSION_NUMBER
FROM "ff_formula_templates" fft;

CREATE OR REPLACE VIEW FF_FORMULA_TEMPLATES_TL AS
SELECT
    TEMPLATE_ID,
    LANGUAGE,
    NAME,
    SOURCE_LANG,
    DESCRIPTION,
    OBJECT_VERSION_NUMBER,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    LAST_UPDATED_BY,
    ENTERPRISE_ID,
    SEED_DATA_SOURCE,
    ORA_SEED_SET1,
    ORA_SEED_SET2
FROM "ff_formula_templates_tl";




CREATE OR REPLACE VIEW FF_FORMULA_TEMPLATES_VL
AS SELECT
    fft.TEMPLATE_ID TEMPLATE_ID,
    fft.FORMULA_TYPE_ID FORMULA_TYPE_ID,
    fft.TEMPLATE_CODE TEMPLATE_CODE,
    fft.FORMULA_TEXT FORMULA_TEXT,
    fft.ADDITIONAL_PROMPT_TEXT ADDITIONAL_PROMPT_TEXT,
    fft.SOURCE_TYPE SOURCE_TYPE,
    fft.SYSTEMPROMPT_FLAG SYSTEMPROMPT_FLAG,
    fft.ACTIVE_FLAG ACTIVE_FLAG,
    fft.SEMANTIC_FLAG SEMANTIC_FLAG,
    fft.SORT_ORDER SORT_ORDER,
    fft.SEED_DATA_SOURCE SEED_DATA_SOURCE,
    fft.CREATED_BY CREATED_BY,
    fft.CREATION_DATE CREATION_DATE,
    fft.LAST_UPDATE_DATE LAST_UPDATE_DATE,
    fft.LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN,
    fft.LAST_UPDATED_BY LAST_UPDATED_BY,
    fft.MODULE_ID MODULE_ID,
    fft.ENTERPRISE_ID ENTERPRISE_ID,
    fft.OBJECT_VERSION_NUMBER OBJECT_VERSION_NUMBER,
    ffttl.NAME NAME,
    ffttl.DESCRIPTION DESCRIPTION
FROM
    FF_FORMULA_TEMPLATES fft,
    FF_FORMULA_TEMPLATES_TL ffttl
WHERE
    fft.TEMPLATE_ID = ffttl.TEMPLATE_ID AND ffttl.LANGUAGE = USERENV('LANG');
