#!/usr/bin/env python3
"""
Generates seed_ff_formula_templates.sql from formula_types_registry.json.

Reads each formula type's sample_prompts and emits one seeded template row
per prompt, with a matching _TL row in US English.

Run:
    python3 java/scripts/generate_seed_templates_sql.py
Output:
    java/scripts/seed_ff_formula_templates.sql
"""
import json
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
JSON_PATH = PROJECT_ROOT / "backend" / "data" / "formula_types_registry.json"
OUTPUT_PATH = PROJECT_ROOT / "java" / "scripts" / "seed_ff_formula_templates.sql"


def sanitize_type_for_code(type_name: str) -> str:
    """Convert a formula type name into a TEMPLATE_CODE-safe UPPER_SNAKE fragment."""
    cleaned = re.sub(r"[^A-Za-z0-9]+", "_", type_name).upper().strip("_")
    # Leave 8 chars headroom for prefix "ORA_FFT_" and suffix "_NNN"
    return cleaned[:130]


def sql_escape(text: str) -> str:
    """Escape a string for a single-quoted SQL literal."""
    # Normalize whitespace (strip newlines/tabs, collapse runs)
    text = text.replace("\r", " ").replace("\n", " ").replace("\t", " ")
    text = re.sub(r"\s+", " ", text).strip()
    # Escape single quotes
    return text.replace("'", "''")


HEADER = """-- ============================================================================
-- Seed data for FF_FORMULA_TEMPLATES / FF_FORMULA_TEMPLATES_TL
--
-- Source: backend/data/formula_types_registry.json (one row per sample_prompt)
-- Target: FUSION."ff_formula_templates" + FUSION."ff_formula_templates_tl"
-- Generated by: java/scripts/generate_seed_templates_sql.py
--
-- IMPORTANT — Fusion physical-name convention:
--   Fusion EBR stores tables as lowercase, double-quoted identifiers
--   ("ff_formula_templates"). Unquoted SQL identifiers are auto-uppercased
--   by Oracle, so INSERT INTO FUSION.ff_formula_templates resolves to the
--   NON-EXISTENT uppercase name FF_FORMULA_TEMPLATES and crashes with
--   ORA-942 or — if a partially-deployed uppercase view is lying around —
--   ORA-600 [5325]. Every table reference in this script is therefore
--   spelled with double-quoted lowercase on purpose. Do NOT change them.
--
-- Properties:
--   SOURCE_TYPE      = SEEDED
--   ACTIVE_FLAG      = Y
--   SEMANTIC_FLAG    = Y
--   MODULE_ID        = HXT
--   ENTERPRISE_ID    = 0
--   CREATED_BY       = SEED_DATA_FROM_APPLICATION
--   SEED_DATA_SOURCE = BULK_SEED_DATA_SCRIPT
--   LANGUAGE         = US (translation rows)
--
-- Notes:
--   * FORMULA_TEXT and ADDITIONAL_PROMPT_TEXT are NULL (prompts are natural
--     language descriptions, not Fast Formula code).
--   * TEMPLATE_ID is generated via FUSION.S_ROW_ID_SEQ.NEXTVAL.
--   * FORMULA_TYPE_ID is looked up from FUSION.FF_FORMULA_TYPES by
--     FORMULA_TYPE_NAME. Rows whose type is not found are SKIPPED
--     (reported via DBMS_OUTPUT). FF_FORMULA_TYPES is a standard Fusion
--     uppercase view so it can stay unquoted.
--   * NOT committed automatically — review output then run COMMIT; or ROLLBACK;
-- ============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET DEFINE OFF
SET LINESIZE 32767
SET FEEDBACK OFF

-- ----------------------------------------------------------------------------
-- Pre-flight: verify the physical FF tables exist.
-- We look in BOTH all_tables (for the lowercase physical tables) AND
-- all_views (for the uppercase wrapper view over FF_FORMULA_TYPES), and
-- match case-insensitively.
-- ----------------------------------------------------------------------------
DECLARE
  v_count NUMBER;
BEGIN
  FOR t IN (
    SELECT 'ff_formula_templates'     AS obj FROM DUAL UNION ALL
    SELECT 'ff_formula_templates_tl'  FROM DUAL UNION ALL
    SELECT 'ff_formula_types'         FROM DUAL
  ) LOOP
    SELECT COUNT(*) INTO v_count
      FROM (SELECT table_name AS name FROM all_tables WHERE owner = 'FUSION'
            UNION ALL
            SELECT view_name   AS name FROM all_views  WHERE owner = 'FUSION')
     WHERE LOWER(name) = LOWER(t.obj);
    IF v_count = 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'Missing FF object: FUSION.' || t.obj);
    END IF;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('Pre-flight OK.');
END;
/

-- ----------------------------------------------------------------------------
-- Warn if prior import exists (script is NOT idempotent — rerun creates dups)
-- ----------------------------------------------------------------------------
DECLARE
  v_existing NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_existing
    FROM FUSION."ff_formula_templates"
   WHERE TEMPLATE_CODE LIKE 'ORA_FFT_%';
  IF v_existing > 0 THEN
    DBMS_OUTPUT.PUT_LINE('WARNING: ' || v_existing || ' rows already have ORA_FFT_ prefix.');
    DBMS_OUTPUT.PUT_LINE('To reimport cleanly, first run:');
    DBMS_OUTPUT.PUT_LINE('  DELETE FROM FUSION."ff_formula_templates_tl"');
    DBMS_OUTPUT.PUT_LINE('    WHERE TEMPLATE_ID IN (SELECT TEMPLATE_ID FROM FUSION."ff_formula_templates"');
    DBMS_OUTPUT.PUT_LINE('                          WHERE TEMPLATE_CODE LIKE ''ORA_FFT_%'');');
    DBMS_OUTPUT.PUT_LINE('  DELETE FROM FUSION."ff_formula_templates" WHERE TEMPLATE_CODE LIKE ''ORA_FFT_%'';');
    DBMS_OUTPUT.PUT_LINE('  COMMIT;');
  END IF;
END;
/

-- ----------------------------------------------------------------------------
-- Main import block
-- ----------------------------------------------------------------------------
DECLARE
  v_inserted NUMBER := 0;
  v_skipped  NUMBER := 0;
  v_id       NUMBER(18);
  v_type_id  NUMBER(18);

  /* Wrap a single row insert so the main body stays readable. */
  PROCEDURE ins (p_type_name IN VARCHAR2,
                 p_code      IN VARCHAR2,
                 p_prompt    IN VARCHAR2) IS
  BEGIN
    BEGIN
      SELECT FORMULA_TYPE_ID
        INTO v_type_id
        FROM FUSION.FF_FORMULA_TYPES
       WHERE FORMULA_TYPE_NAME = p_type_name
         AND ROWNUM = 1;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('SKIP: ' || p_code || ' (type not in FF_FORMULA_TYPES: ' || p_type_name || ')');
        v_skipped := v_skipped + 1;
        RETURN;
    END;

    v_id := FUSION.S_ROW_ID_SEQ.NEXTVAL;

    INSERT INTO FUSION."ff_formula_templates" (
      TEMPLATE_ID, FORMULA_TYPE_ID, TEMPLATE_CODE, FORMULA_TEXT, ADDITIONAL_PROMPT_TEXT,
      SOURCE_TYPE, ACTIVE_FLAG, SEMANTIC_FLAG, SORT_ORDER,
      OBJECT_VERSION_NUMBER, LAST_UPDATE_DATE, CREATED_BY, CREATION_DATE,
      LAST_UPDATED_BY, LAST_UPDATE_LOGIN,
      ENTERPRISE_ID, SEED_DATA_SOURCE, MODULE_ID, ORA_SEED_SET1, ORA_SEED_SET2
    ) VALUES (
      v_id, v_type_id, p_code, NULL, NULL,
      'SEEDED', 'Y', 'Y', NULL,
      1, SYSTIMESTAMP, 'SEED_DATA_FROM_APPLICATION', SYSTIMESTAMP,
      'SEED_DATA_FROM_APPLICATION', NULL,
      0, 'BULK_SEED_DATA_SCRIPT', 'HXT', 'Y', 'Y'
    );

    INSERT INTO FUSION."ff_formula_templates_tl" (
      TEMPLATE_ID, LANGUAGE, NAME, SOURCE_LANG, DESCRIPTION,
      OBJECT_VERSION_NUMBER, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE,
      LAST_UPDATE_LOGIN, LAST_UPDATED_BY,
      ENTERPRISE_ID, SEED_DATA_SOURCE, ORA_SEED_SET1, ORA_SEED_SET2
    ) VALUES (
      v_id, 'US', SUBSTR(p_prompt, 1, 240), 'US', p_prompt,
      1, 'SEED_DATA_FROM_APPLICATION', SYSTIMESTAMP, SYSTIMESTAMP,
      NULL, 'SEED_DATA_FROM_APPLICATION',
      0, 'BULK_SEED_DATA_SCRIPT', 'Y', 'Y'
    );

    v_inserted := v_inserted + 1;
  END ins;

BEGIN
"""

FOOTER = """
  DBMS_OUTPUT.PUT_LINE('============================================');
  DBMS_OUTPUT.PUT_LINE('Import summary:');
  DBMS_OUTPUT.PUT_LINE('  Inserted: ' || v_inserted);
  DBMS_OUTPUT.PUT_LINE('  Skipped : ' || v_skipped);
  DBMS_OUTPUT.PUT_LINE('============================================');
  DBMS_OUTPUT.PUT_LINE('Review output. Then run COMMIT; to save, or ROLLBACK; to discard.');
END;
/

SET FEEDBACK ON
"""


def main() -> int:
    if not JSON_PATH.exists():
        print(f"ERROR: {JSON_PATH} not found", file=sys.stderr)
        return 1

    with JSON_PATH.open() as f:
        types = json.load(f)

    lines: list[str] = []
    total_prompts = 0
    total_types = 0
    skipped_empty_types = 0
    for type_info in types:
        type_name = type_info.get("type_name", "").strip()
        prompts = type_info.get("sample_prompts", []) or []
        if not type_name:
            continue
        if not prompts:
            skipped_empty_types += 1
            continue
        total_types += 1
        code_base = sanitize_type_for_code(type_name)
        escaped_type = sql_escape(type_name)
        for idx, prompt in enumerate(prompts, start=1):
            prompt = (prompt or "").strip()
            if not prompt:
                continue
            code = f"ORA_FFT_{code_base}_{idx:03d}"
            if len(code) > 150:
                code = code[:150]
            escaped_prompt = sql_escape(prompt)[:4000]
            lines.append(
                f"  ins('{escaped_type}', '{code}', '{escaped_prompt}');"
            )
            total_prompts += 1

    sql = HEADER + "\n".join(lines) + "\n" + FOOTER

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(sql, encoding="utf-8")

    size_kb = len(sql) / 1024
    print(f"Generated {OUTPUT_PATH}")
    print(f"  Formula types with prompts: {total_types}")
    print(f"  Formula types with 0 prompts (skipped): {skipped_empty_types}")
    print(f"  Total ins() calls: {total_prompts}")
    print(f"  File size: {size_kb:.1f} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
