select * from FF_FORMULA_TEMPLATES_VL where formula_type_id is null;

CREATE VIEW FF_FORMULA_TEMPLATES_VL
AS SELECT
    fft.TEMPLATE_ID TEMPLATE_ID,
    fft.FORMULA_TYPE_ID FORMULA_TYPE_ID,
    fft.TEMPLATE_CODE TEMPLATE_CODE,
    fft.FORMULA_TEXT FORMULA_TEXT,
    fft.ADDITIONAL_PROMPT_TEXT ADDITIONAL_PROMPT_TEXT,
    fft.SOURCE_TYPE SOURCE_TYPE,
    fft.ACTIVE_FLAG ACTIVE_FLAG,
    fft.SEMANTIC_FLAG SEMANTIC_FLAG,
    fft.SORT_ORDER SORT_ORDER,
    fft.SEED_DATA_SOURCE SEED_DATA_SOURCE,
    fft.CREATED_BY CREATED_BY,
    fft.CREATION_DATE CREATION_DATE,
    fft.LAST_UPDATE_DATE LAST_UPDATE_DATE,
    fft.LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN,
    fft.LAST_UPDATED_BY LAST_UPDATED_BY,
    fft.MODULE_ID MODULE_ID,
    fft.ENTERPRISE_ID ENTERPRISE_ID,
    fft.OBJECT_VERSION_NUMBER OBJECT_VERSION_NUMBER,
    ffttl.NAME NAME,
    ffttl.DESCRIPTION DESCRIPTION
FROM
    FF_FORMULA_TEMPLATES fft,
    FF_FORMULA_TEMPLATES_TL ffttl
WHERE
    fft.TEMPLATE_ID = ffttl.TEMPLATE_ID AND ffttl.LANGUAGE = USERENV('LANG');

     
INSERT INTO FUSION."ff_formula_templates" (
    TEMPLATE_ID, FORMULA_TYPE_ID, TEMPLATE_CODE,
    FORMULA_TEXT, ADDITIONAL_PROMPT_TEXT,
    SOURCE_TYPE, ACTIVE_FLAG, SEMANTIC_FLAG, SORT_ORDER,
    OBJECT_VERSION_NUMBER, LAST_UPDATE_DATE, CREATED_BY, CREATION_DATE,
    LAST_UPDATED_BY, LAST_UPDATE_LOGIN,
    ENTERPRISE_ID, SEED_DATA_SOURCE, MODULE_ID,
    ORA_SEED_SET1, ORA_SEED_SET2
  ) VALUES (
    9999001, NULL, 'TEST_BASE_001',
    NULL, NULL,
    'USER_CREATED', 'Y', 'Y', NULL,
    1, SYSTIMESTAMP, 'TEST', SYSTIMESTAMP,
    'TEST', NULL,
    0, 'MANUAL_TEST', 'HXT',
    'Y', 'Y'
  );
  
  INSERT INTO FUSION."ff_formula_templates_tl" (
    TEMPLATE_ID, LANGUAGE, NAME, SOURCE_LANG, DESCRIPTION,
    OBJECT_VERSION_NUMBER,
    CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN, LAST_UPDATED_BY,
    ENTERPRISE_ID, SEED_DATA_SOURCE,
    ORA_SEED_SET1, ORA_SEED_SET2
  ) VALUES (
    9999001, 'US', 'Test TL Row', 'US',
    'Minimal TL insert test',
    1,
    'TEST', SYSTIMESTAMP, SYSTIMESTAMP,
    NULL, 'TEST',
    0, 'MANUAL_TEST',
    'Y', 'Y'
  );
  
  
  drop table "ff_formula_templates_tl";
  
  select * from "ff_formula_templates_tl";
select * from FF_FORMULA_TEMPLATES_TL;



CREATE TABLE "ff_formula_templates_tl" 
(
  TEMPLATE_ID NUMBER(18, 0) NOT NULL 
, LANGUAGE VARCHAR2(4) NOT NULL 
, NAME VARCHAR2(240) NOT NULL 
, SOURCE_LANG VARCHAR2(4) NOT NULL 
, DESCRIPTION VARCHAR2(4000) 
, OBJECT_VERSION_NUMBER NUMBER(9, 0) DEFAULT 1 NOT NULL 
, CREATED_BY VARCHAR2(64) NOT NULL 
, CREATION_DATE TIMESTAMP NOT NULL 
, LAST_UPDATE_DATE TIMESTAMP NOT NULL 
, LAST_UPDATE_LOGIN VARCHAR2(32) 
, LAST_UPDATED_BY VARCHAR2(64) NOT NULL 
, ENTERPRISE_ID NUMBER(18, 0) DEFAULT nvl(SYS_CONTEXT('FND_VPD_CTX','FND_ENTERPRISE_ID'), 0) NOT NULL 
, SEED_DATA_SOURCE VARCHAR2(512) DEFAULT SYS_CONTEXT('FND_SDF_CTX', 'SDFFILE') NOT NULL 
, ORA_SEED_SET1 VARCHAR2(1) DEFAULT 'Y' NOT NULL 
, ORA_SEED_SET2 VARCHAR2(1) DEFAULT 'Y' NOT NULL 
);

CREATE OR REPLACE VIEW FF_FORMULA_TEMPLATES_TL AS
SELECT
    TEMPLATE_ID,
    LANGUAGE,
    NAME,
    SOURCE_LANG,
    DESCRIPTION,
    OBJECT_VERSION_NUMBER,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    LAST_UPDATED_BY,
    ENTERPRISE_ID,
    SEED_DATA_SOURCE,
    ORA_SEED_SET1,
    ORA_SEED_SET2
FROM "ff_formula_templates_tl";
